package sms

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"log"
	"net/http"
	"net/url"
	"strings"
	"time"
)

// TwoFactorSMSService sends OTP SMS via the 2factor.in transactional OTP API.
// It uses the "custom OTP" endpoint where the OTP value is generated by us and
// passed in the URL, so verification is done against our own database.
type TwoFactorSMSService struct {
	APIKey  string
	BaseURL string
	Client  *http.Client
}

// NewTwoFactorSMSService creates a new TwoFactorSMSService using the given API key.
func NewTwoFactorSMSService(apiKey string) *TwoFactorSMSService {
	return &TwoFactorSMSService{
		APIKey:  apiKey,
		BaseURL: "https://2factor.in/API/V1",
		Client:  &http.Client{Timeout: 10 * time.Second},
	}
}

// twoFactorResponse is the JSON envelope returned by the 2factor.in API.
type twoFactorResponse struct {
	Status  string `json:"Status"`
	Details string `json:"Details"`
}

// SendOTPSMSWithCtx sends the given OTP to phone using the 2factor.in API.
// Endpoint: https://2factor.in/API/V1/:api_key/SMS/:phone_number/:otp_value/otp
func (t *TwoFactorSMSService) SendOTPSMSWithCtx(ctx context.Context, phone, otp string) error {
	if t == nil {
		return errors.New("2factor service not initialized")
	}
	if t.APIKey == "" {
		return errors.New("2factor API key missing")
	}

	endpoint := fmt.Sprintf("%s/%s/SMS/%s/%s/otp",
		t.BaseURL,
		url.PathEscape(t.APIKey),
		url.PathEscape(phone),
		url.PathEscape(otp),
	)

	log.Printf("[2factor] sending OTP SMS to phone=%s", phone)

	req, err := http.NewRequestWithContext(ctx, http.MethodGet, endpoint, nil)
	if err != nil {
		log.Printf("[2factor] failed to build request: %v", err)
		return err
	}

	resp, err := t.Client.Do(req)
	if err != nil {
		log.Printf("[2factor] HTTP request failed: %v", err)
		return err
	}
	defer resp.Body.Close()

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return err
	}

	log.Printf("[2factor] response status=%s body=%s", resp.Status, strings.TrimSpace(string(body)))

	if resp.StatusCode >= 400 {
		return fmt.Errorf("2factor send failed: %s: %s", resp.Status, strings.TrimSpace(string(body)))
	}

	var parsed twoFactorResponse
	if err := json.Unmarshal(body, &parsed); err != nil {
		return fmt.Errorf("2factor unexpected response: %s", strings.TrimSpace(string(body)))
	}
	if !strings.EqualFold(parsed.Status, "Success") {
		log.Printf("[2factor] API returned failure: %s", parsed.Details)
		return fmt.Errorf("2factor send failed: %s", parsed.Details)
	}

	log.Printf("[2factor] OTP SMS sent successfully to phone=%s session=%s", phone, parsed.Details)
	return nil
}

// SendOTPSMS sends an OTP using a background context.
func (t *TwoFactorSMSService) SendOTPSMS(phone, otp string) error {
	return t.SendOTPSMSWithCtx(context.Background(), phone, otp)
}
