version: '3'
services:
# database container
  postgresdb:
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: rohitjangid
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: mandi
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - ecommerce-network
# webapp container
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: rohit221990/mandi-backend
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      - DB_HOST=postgresdb
    depends_on:
      - postgresdb
    restart: always
    networks:
      - ecommerce-network

# for persistent data storage
volumes:
  database:

networks:
  ecommerce-network:
    driver: bridge
 