// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/repository/interfaces/invoice.go

// Package mockrepo is a generated GoMock package.
package mockrepo

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domain "github.com/rohit221990/mandi-backend/pkg/domain"
)

// MockInvoiceRepository is a mock of InvoiceRepository interface.
type MockInvoiceRepository struct {
	ctrl     *gomock.Controller
	recorder *MockInvoiceRepositoryMockRecorder
}

// MockInvoiceRepositoryMockRecorder is the mock recorder for MockInvoiceRepository.
type MockInvoiceRepositoryMockRecorder struct {
	mock *MockInvoiceRepository
}

// NewMockInvoiceRepository creates a new mock instance.
func NewMockInvoiceRepository(ctrl *gomock.Controller) *MockInvoiceRepository {
	mock := &MockInvoiceRepository{ctrl: ctrl}
	mock.recorder = &MockInvoiceRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInvoiceRepository) EXPECT() *MockInvoiceRepositoryMockRecorder {
	return m.recorder
}

// GetCompanyBillingProfile mocks base method.
func (m *MockInvoiceRepository) GetCompanyBillingProfile(ctx context.Context) (domain.CompanyBillingProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCompanyBillingProfile", ctx)
	ret0, _ := ret[0].(domain.CompanyBillingProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCompanyBillingProfile indicates an expected call of GetCompanyBillingProfile.
func (mr *MockInvoiceRepositoryMockRecorder) GetCompanyBillingProfile(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCompanyBillingProfile", reflect.TypeOf((*MockInvoiceRepository)(nil).GetCompanyBillingProfile), ctx)
}

// UpdateCompanyBillingProfile mocks base method.
func (m *MockInvoiceRepository) UpdateCompanyBillingProfile(ctx context.Context, profile domain.CompanyBillingProfile) (domain.CompanyBillingProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCompanyBillingProfile", ctx, profile)
	ret0, _ := ret[0].(domain.CompanyBillingProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCompanyBillingProfile indicates an expected call of UpdateCompanyBillingProfile.
func (mr *MockInvoiceRepositoryMockRecorder) UpdateCompanyBillingProfile(ctx, profile interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCompanyBillingProfile", reflect.TypeOf((*MockInvoiceRepository)(nil).UpdateCompanyBillingProfile), ctx, profile)
}
