// Code generated by manual creation. DO NOT EDIT.
// Source: pkg/repository/interfaces/search.go

// Package mockrepo is a generated GoMock package.
package mockrepo

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	response "github.com/rohit221990/mandi-backend/pkg/api/handler/response"
)

// MockSearchRepository is a mock of SearchRepository interface.
type MockSearchRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSearchRepositoryMockRecorder
}

// MockSearchRepositoryMockRecorder is the mock recorder for MockSearchRepository.
type MockSearchRepositoryMockRecorder struct {
	mock *MockSearchRepository
}

// NewMockSearchRepository creates a new mock instance.
func NewMockSearchRepository(ctrl *gomock.Controller) *MockSearchRepository {
	mock := &MockSearchRepository{ctrl: ctrl}
	mock.recorder = &MockSearchRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSearchRepository) EXPECT() *MockSearchRepositoryMockRecorder {
	return m.recorder
}

// GlobalSearch mocks base method.
func (m *MockSearchRepository) GlobalSearch(ctx context.Context, query string, entityTypes []string,
	lat, lng, radiusKm float64, pincode string, limit, offset uint) (response.GlobalSearchResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GlobalSearch", ctx, query, entityTypes, lat, lng, radiusKm, pincode, limit, offset)
	ret0, _ := ret[0].(response.GlobalSearchResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GlobalSearch indicates an expected call of GlobalSearch.
func (mr *MockSearchRepositoryMockRecorder) GlobalSearch(ctx, query, entityTypes, lat, lng, radiusKm, pincode, limit, offset interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GlobalSearch", reflect.TypeOf((*MockSearchRepository)(nil).GlobalSearch), ctx, query, entityTypes, lat, lng, radiusKm, pincode, limit, offset)
}

// AutocompleteSuggestions mocks base method.
func (m *MockSearchRepository) AutocompleteSuggestions(ctx context.Context, prefix string, limit uint) ([]response.AutocompleteSuggestion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AutocompleteSuggestions", ctx, prefix, limit)
	ret0, _ := ret[0].([]response.AutocompleteSuggestion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AutocompleteSuggestions indicates an expected call of AutocompleteSuggestions.
func (mr *MockSearchRepositoryMockRecorder) AutocompleteSuggestions(ctx, prefix, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AutocompleteSuggestions", reflect.TypeOf((*MockSearchRepository)(nil).AutocompleteSuggestions), ctx, prefix, limit)
}

// SearchTaxonomy mocks base method.
func (m *MockSearchRepository) SearchTaxonomy(ctx context.Context, query, departmentID string, limit uint) ([]response.TaxonomySearchItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchTaxonomy", ctx, query, departmentID, limit)
	ret0, _ := ret[0].([]response.TaxonomySearchItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchTaxonomy indicates an expected call of SearchTaxonomy.
func (mr *MockSearchRepositoryMockRecorder) SearchTaxonomy(ctx, query, departmentID, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchTaxonomy", reflect.TypeOf((*MockSearchRepository)(nil).SearchTaxonomy), ctx, query, departmentID, limit)
}
