// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/repository/interfaces/user.go

// Package mockrepo is a generated GoMock package.
package mockrepo

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	request "github.com/rohit221990/mandi-backend/pkg/api/handler/request"
	response "github.com/rohit221990/mandi-backend/pkg/api/handler/response"
	domain "github.com/rohit221990/mandi-backend/pkg/domain"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// DeleteRefreshSessionByUserID mocks base method.
func (m *MockUserRepository) DeleteRefreshSessionByUserID(ctx context.Context, adminID, userType string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRefreshSessionByUserID", ctx, adminID, userType)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRefreshSessionByUserID indicates an expected call of DeleteRefreshSessionByUserID.
func (mr *MockUserRepositoryMockRecorder) DeleteRefreshSessionByUserID(ctx, adminID, userType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRefreshSessionByUserID", reflect.TypeOf((*MockUserRepository)(nil).DeleteRefreshSessionByUserID), ctx, adminID, userType)
}

// FindAddressByID mocks base method.
func (m *MockUserRepository) FindAddressByID(ctx context.Context, addressID string) (response.Address, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAddressByID", ctx, addressID)
	ret0, _ := ret[0].(response.Address)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAddressByID indicates an expected call of FindAddressByID.
func (mr *MockUserRepositoryMockRecorder) FindAddressByID(ctx, addressID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAddressByID", reflect.TypeOf((*MockUserRepository)(nil).FindAddressByID), ctx, addressID)
}

// FindAllAddressByUserID mocks base method.
func (m *MockUserRepository) FindAllAddressByUserID(ctx context.Context, userID string) ([]response.Address, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllAddressByUserID", ctx, userID)
	ret0, _ := ret[0].([]response.Address)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllAddressByUserID indicates an expected call of FindAllAddressByUserID.
func (mr *MockUserRepositoryMockRecorder) FindAllAddressByUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllAddressByUserID", reflect.TypeOf((*MockUserRepository)(nil).FindAllAddressByUserID), ctx, userID)
}

// FindAllWishListItemsByUserID mocks base method.
func (m *MockUserRepository) FindAllWishListItemsByUserID(ctx context.Context, userID string) ([]response.WishListItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllWishListItemsByUserID", ctx, userID)
	ret0, _ := ret[0].([]response.WishListItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllWishListItemsByUserID indicates an expected call of FindAllWishListItemsByUserID.
func (mr *MockUserRepositoryMockRecorder) FindAllWishListItemsByUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllWishListItemsByUserID", reflect.TypeOf((*MockUserRepository)(nil).FindAllWishListItemsByUserID), ctx, userID)
}

// FindCountryByID mocks base method.
func (m *MockUserRepository) FindCountryByID(ctx context.Context, countryID string) (domain.Country, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindCountryByID", ctx, countryID)
	ret0, _ := ret[0].(domain.Country)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindCountryByID indicates an expected call of FindCountryByID.
func (mr *MockUserRepositoryMockRecorder) FindCountryByID(ctx, countryID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindCountryByID", reflect.TypeOf((*MockUserRepository)(nil).FindCountryByID), ctx, countryID)
}

// FindSellersByPincode mocks base method.
func (m *MockUserRepository) FindSellersByPincode(ctx context.Context, reqData request.SellerPincodeRequest) ([]response.Shop, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindSellersByPincode", ctx, reqData)
	ret0, _ := ret[0].([]response.Shop)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindSellersByPincode indicates an expected call of FindSellersByPincode.
func (mr *MockUserRepositoryMockRecorder) FindSellersByPincode(ctx, reqData interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindSellersByPincode", reflect.TypeOf((*MockUserRepository)(nil).FindSellersByPincode), ctx, reqData)
}

// FindSellersByRadius mocks base method.
func (m *MockUserRepository) FindSellersByRadius(ctx context.Context, reqData request.SellerRadiusRequest) ([]response.Shop, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindSellersByRadius", ctx, reqData)
	ret0, _ := ret[0].([]response.Shop)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindSellersByRadius indicates an expected call of FindSellersByRadius.
func (mr *MockUserRepositoryMockRecorder) FindSellersByRadius(ctx, reqData interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindSellersByRadius", reflect.TypeOf((*MockUserRepository)(nil).FindSellersByRadius), ctx, reqData)
}

// FindShopByID mocks base method.
func (m *MockUserRepository) FindShopByID(ctx context.Context, shopID string) (response.Shop, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindShopByID", ctx, shopID)
	ret0, _ := ret[0].(response.Shop)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindShopByID indicates an expected call of FindShopByID.
func (mr *MockUserRepositoryMockRecorder) FindShopByID(ctx, shopID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindShopByID", reflect.TypeOf((*MockUserRepository)(nil).FindShopByID), ctx, shopID)
}

// FindUserByEmail mocks base method.
func (m *MockUserRepository) FindUserByEmail(ctx context.Context, email string) (domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserByEmail", ctx, email)
	ret0, _ := ret[0].(domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUserByEmail indicates an expected call of FindUserByEmail.
func (mr *MockUserRepositoryMockRecorder) FindUserByEmail(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserByEmail", reflect.TypeOf((*MockUserRepository)(nil).FindUserByEmail), ctx, email)
}

// FindUserByPhoneNumber mocks base method.
func (m *MockUserRepository) FindUserByPhoneNumber(ctx context.Context, phoneNumber string) (domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserByPhoneNumber", ctx, phoneNumber)
	ret0, _ := ret[0].(domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUserByPhoneNumber indicates an expected call of FindUserByPhoneNumber.
func (mr *MockUserRepositoryMockRecorder) FindUserByPhoneNumber(ctx, phoneNumber interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserByPhoneNumber", reflect.TypeOf((*MockUserRepository)(nil).FindUserByPhoneNumber), ctx, phoneNumber)
}

// FindUserByUserID mocks base method.
func (m *MockUserRepository) FindUserByUserID(ctx context.Context, userID string) (domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserByUserID", ctx, userID)
	ret0, _ := ret[0].(domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUserByUserID indicates an expected call of FindUserByUserID.
func (mr *MockUserRepositoryMockRecorder) FindUserByUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserByUserID", reflect.TypeOf((*MockUserRepository)(nil).FindUserByUserID), ctx, userID)
}

// FindUserByUserName mocks base method.
func (m *MockUserRepository) FindUserByUserName(ctx context.Context, userName string) (domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserByUserName", ctx, userName)
	ret0, _ := ret[0].(domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUserByUserName indicates an expected call of FindUserByUserName.
func (mr *MockUserRepositoryMockRecorder) FindUserByUserName(ctx, userName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserByUserName", reflect.TypeOf((*MockUserRepository)(nil).FindUserByUserName), ctx, userName)
}

// FindUserByUserNameEmailOrPhoneNotID mocks base method.
func (m *MockUserRepository) FindUserByUserNameEmailOrPhoneNotID(ctx context.Context, user domain.User) (domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserByUserNameEmailOrPhoneNotID", ctx, user)
	ret0, _ := ret[0].(domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUserByUserNameEmailOrPhoneNotID indicates an expected call of FindUserByUserNameEmailOrPhoneNotID.
func (mr *MockUserRepositoryMockRecorder) FindUserByUserNameEmailOrPhoneNotID(ctx, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserByUserNameEmailOrPhoneNotID", reflect.TypeOf((*MockUserRepository)(nil).FindUserByUserNameEmailOrPhoneNotID), ctx, user)
}

// FindWishListItem mocks base method.
func (m *MockUserRepository) FindWishListItem(ctx context.Context, productID, userID string) (domain.WishList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindWishListItem", ctx, productID, userID)
	ret0, _ := ret[0].(domain.WishList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindWishListItem indicates an expected call of FindWishListItem.
func (mr *MockUserRepositoryMockRecorder) FindWishListItem(ctx, productID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindWishListItem", reflect.TypeOf((*MockUserRepository)(nil).FindWishListItem), ctx, productID, userID)
}

// FollowShop mocks base method.
func (m *MockUserRepository) FollowShop(ctx context.Context, userID, shopID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FollowShop", ctx, userID, shopID)
	ret0, _ := ret[0].(error)
	return ret0
}

// FollowShop indicates an expected call of FollowShop.
func (mr *MockUserRepositoryMockRecorder) FollowShop(ctx, userID, shopID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FollowShop", reflect.TypeOf((*MockUserRepository)(nil).FollowShop), ctx, userID, shopID)
}

// GetAllShopRatings mocks base method.
func (m *MockUserRepository) GetAllShopRatings(ctx context.Context, shopID string) ([]domain.ShopSocial, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllShopRatings", ctx, shopID)
	ret0, _ := ret[0].([]domain.ShopSocial)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllShopRatings indicates an expected call of GetAllShopRatings.
func (mr *MockUserRepositoryMockRecorder) GetAllShopRatings(ctx, shopID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllShopRatings", reflect.TypeOf((*MockUserRepository)(nil).GetAllShopRatings), ctx, shopID)
}

// GetAllShopReviews mocks base method.
func (m *MockUserRepository) GetAllShopReviews(ctx context.Context, shopID string) ([]domain.ShopSocial, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllShopReviews", ctx, shopID)
	ret0, _ := ret[0].([]domain.ShopSocial)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllShopReviews indicates an expected call of GetAllShopReviews.
func (mr *MockUserRepositoryMockRecorder) GetAllShopReviews(ctx, shopID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllShopReviews", reflect.TypeOf((*MockUserRepository)(nil).GetAllShopReviews), ctx, shopID)
}

// GetFollowedShops mocks base method.
func (m *MockUserRepository) GetFollowedShops(ctx context.Context, userID string) ([]response.Shop, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFollowedShops", ctx, userID)
	ret0, _ := ret[0].([]response.Shop)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFollowedShops indicates an expected call of GetFollowedShops.
func (mr *MockUserRepositoryMockRecorder) GetFollowedShops(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFollowedShops", reflect.TypeOf((*MockUserRepository)(nil).GetFollowedShops), ctx, userID)
}

// GetFollowers mocks base method.
func (m *MockUserRepository) GetFollowers(ctx context.Context, shopID string) ([]response.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFollowers", ctx, shopID)
	ret0, _ := ret[0].([]response.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFollowers indicates an expected call of GetFollowers.
func (mr *MockUserRepositoryMockRecorder) GetFollowers(ctx, shopID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFollowers", reflect.TypeOf((*MockUserRepository)(nil).GetFollowers), ctx, shopID)
}

// GetLikedShops mocks base method.
func (m *MockUserRepository) GetLikedShops(ctx context.Context, userID string) ([]response.Shop, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLikedShops", ctx, userID)
	ret0, _ := ret[0].([]response.Shop)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLikedShops indicates an expected call of GetLikedShops.
func (mr *MockUserRepositoryMockRecorder) GetLikedShops(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLikedShops", reflect.TypeOf((*MockUserRepository)(nil).GetLikedShops), ctx, userID)
}

// GetShopAverageRating mocks base method.
func (m *MockUserRepository) GetShopAverageRating(ctx context.Context, shopID string) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetShopAverageRating", ctx, shopID)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetShopAverageRating indicates an expected call of GetShopAverageRating.
func (mr *MockUserRepositoryMockRecorder) GetShopAverageRating(ctx, shopID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetShopAverageRating", reflect.TypeOf((*MockUserRepository)(nil).GetShopAverageRating), ctx, shopID)
}

// GetShopRatingDistribution mocks base method.
func (m *MockUserRepository) GetShopRatingDistribution(ctx context.Context, shopID string) ([]domain.ShopRatingDistribution, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetShopRatingDistribution", ctx, shopID)
	ret0, _ := ret[0].([]domain.ShopRatingDistribution)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetShopRatingDistribution indicates an expected call of GetShopRatingDistribution.
func (mr *MockUserRepositoryMockRecorder) GetShopRatingDistribution(ctx, shopID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetShopRatingDistribution", reflect.TypeOf((*MockUserRepository)(nil).GetShopRatingDistribution), ctx, shopID)
}

// GetShopSocialDetails mocks base method.
func (m *MockUserRepository) GetShopSocialDetails(ctx context.Context, shopID, userID string) (domain.ShopSocialSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetShopSocialDetails", ctx, shopID, userID)
	ret0, _ := ret[0].(domain.ShopSocialSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetShopSocialDetails indicates an expected call of GetShopSocialDetails.
func (mr *MockUserRepositoryMockRecorder) GetShopSocialDetails(ctx, shopID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetShopSocialDetails", reflect.TypeOf((*MockUserRepository)(nil).GetShopSocialDetails), ctx, shopID, userID)
}

// GetUserShopRating mocks base method.
func (m *MockUserRepository) GetUserShopRating(ctx context.Context, userID, shopID string) (uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserShopRating", ctx, userID, shopID)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserShopRating indicates an expected call of GetUserShopRating.
func (mr *MockUserRepositoryMockRecorder) GetUserShopRating(ctx, userID, shopID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserShopRating", reflect.TypeOf((*MockUserRepository)(nil).GetUserShopRating), ctx, userID, shopID)
}

// GetUserShopReview mocks base method.
func (m *MockUserRepository) GetUserShopReview(ctx context.Context, userID, shopID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserShopReview", ctx, userID, shopID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserShopReview indicates an expected call of GetUserShopReview.
func (mr *MockUserRepositoryMockRecorder) GetUserShopReview(ctx, userID, shopID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserShopReview", reflect.TypeOf((*MockUserRepository)(nil).GetUserShopReview), ctx, userID, shopID)
}

// IsAddressAlreadyExistForUser mocks base method.
func (m *MockUserRepository) IsAddressAlreadyExistForUser(ctx context.Context, address domain.Address, userID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAddressAlreadyExistForUser", ctx, address, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsAddressAlreadyExistForUser indicates an expected call of IsAddressAlreadyExistForUser.
func (mr *MockUserRepositoryMockRecorder) IsAddressAlreadyExistForUser(ctx, address, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAddressAlreadyExistForUser", reflect.TypeOf((*MockUserRepository)(nil).IsAddressAlreadyExistForUser), ctx, address, userID)
}

// IsAddressIDExist mocks base method.
func (m *MockUserRepository) IsAddressIDExist(ctx context.Context, addressID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAddressIDExist", ctx, addressID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsAddressIDExist indicates an expected call of IsAddressIDExist.
func (mr *MockUserRepositoryMockRecorder) IsAddressIDExist(ctx, addressID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAddressIDExist", reflect.TypeOf((*MockUserRepository)(nil).IsAddressIDExist), ctx, addressID)
}

// IsFollowingShop mocks base method.
func (m *MockUserRepository) IsFollowingShop(ctx context.Context, userID, shopID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsFollowingShop", ctx, userID, shopID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsFollowingShop indicates an expected call of IsFollowingShop.
func (mr *MockUserRepositoryMockRecorder) IsFollowingShop(ctx, userID, shopID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsFollowingShop", reflect.TypeOf((*MockUserRepository)(nil).IsFollowingShop), ctx, userID, shopID)
}

// IsLikedShop mocks base method.
func (m *MockUserRepository) IsLikedShop(ctx context.Context, userID, shopID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsLikedShop", ctx, userID, shopID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsLikedShop indicates an expected call of IsLikedShop.
func (mr *MockUserRepositoryMockRecorder) IsLikedShop(ctx, userID, shopID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsLikedShop", reflect.TypeOf((*MockUserRepository)(nil).IsLikedShop), ctx, userID, shopID)
}

// IsTrialUsed mocks base method.
func (m *MockUserRepository) IsTrialUsed(ctx context.Context, userID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsTrialUsed", ctx, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsTrialUsed indicates an expected call of IsTrialUsed.
func (mr *MockUserRepositoryMockRecorder) IsTrialUsed(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsTrialUsed", reflect.TypeOf((*MockUserRepository)(nil).IsTrialUsed), ctx, userID)
}

// LikeShop mocks base method.
func (m *MockUserRepository) LikeShop(ctx context.Context, userID, shopID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LikeShop", ctx, userID, shopID)
	ret0, _ := ret[0].(error)
	return ret0
}

// LikeShop indicates an expected call of LikeShop.
func (mr *MockUserRepositoryMockRecorder) LikeShop(ctx, userID, shopID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LikeShop", reflect.TypeOf((*MockUserRepository)(nil).LikeShop), ctx, userID, shopID)
}

// RateShop mocks base method.
func (m *MockUserRepository) RateShop(ctx context.Context, userID, shopID string, rating uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RateShop", ctx, userID, shopID, rating)
	ret0, _ := ret[0].(error)
	return ret0
}

// RateShop indicates an expected call of RateShop.
func (mr *MockUserRepositoryMockRecorder) RateShop(ctx, userID, shopID, rating interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RateShop", reflect.TypeOf((*MockUserRepository)(nil).RateShop), ctx, userID, shopID, rating)
}

// RemoveWishListItem mocks base method.
func (m *MockUserRepository) RemoveWishListItem(ctx context.Context, userID, productItemID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveWishListItem", ctx, userID, productItemID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveWishListItem indicates an expected call of RemoveWishListItem.
func (mr *MockUserRepositoryMockRecorder) RemoveWishListItem(ctx, userID, productItemID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveWishListItem", reflect.TypeOf((*MockUserRepository)(nil).RemoveWishListItem), ctx, userID, productItemID)
}

// ReviewShop mocks base method.
func (m *MockUserRepository) ReviewShop(ctx context.Context, userID, shopID, review string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReviewShop", ctx, userID, shopID, review)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReviewShop indicates an expected call of ReviewShop.
func (mr *MockUserRepositoryMockRecorder) ReviewShop(ctx, userID, shopID, review interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReviewShop", reflect.TypeOf((*MockUserRepository)(nil).ReviewShop), ctx, userID, shopID, review)
}

// SaveAddress mocks base method.
func (m *MockUserRepository) SaveAddress(ctx context.Context, address domain.Address) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveAddress", ctx, address)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveAddress indicates an expected call of SaveAddress.
func (mr *MockUserRepositoryMockRecorder) SaveAddress(ctx, address interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveAddress", reflect.TypeOf((*MockUserRepository)(nil).SaveAddress), ctx, address)
}

// SaveUser mocks base method.
func (m *MockUserRepository) SaveUser(ctx context.Context, user domain.User) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveUser", ctx, user)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveUser indicates an expected call of SaveUser.
func (mr *MockUserRepositoryMockRecorder) SaveUser(ctx, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveUser", reflect.TypeOf((*MockUserRepository)(nil).SaveUser), ctx, user)
}

// SaveUserAddress mocks base method.
func (m *MockUserRepository) SaveUserAddress(ctx context.Context, userAdress domain.UserAddress) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveUserAddress", ctx, userAdress)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveUserAddress indicates an expected call of SaveUserAddress.
func (mr *MockUserRepositoryMockRecorder) SaveUserAddress(ctx, userAdress interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveUserAddress", reflect.TypeOf((*MockUserRepository)(nil).SaveUserAddress), ctx, userAdress)
}

// SaveWishListItem mocks base method.
func (m *MockUserRepository) SaveWishListItem(ctx context.Context, wishList domain.WishList) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveWishListItem", ctx, wishList)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveWishListItem indicates an expected call of SaveWishListItem.
func (mr *MockUserRepositoryMockRecorder) SaveWishListItem(ctx, wishList interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveWishListItem", reflect.TypeOf((*MockUserRepository)(nil).SaveWishListItem), ctx, wishList)
}

// SearchShopList mocks base method.
func (m *MockUserRepository) SearchShopList(ctx context.Context, reqData request.SearchShopListRequest) ([]response.Shop, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchShopList", ctx, reqData)
	ret0, _ := ret[0].([]response.Shop)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchShopList indicates an expected call of SearchShopList.
func (mr *MockUserRepositoryMockRecorder) SearchShopList(ctx, reqData interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchShopList", reflect.TypeOf((*MockUserRepository)(nil).SearchShopList), ctx, reqData)
}

// UnfollowShop mocks base method.
func (m *MockUserRepository) UnfollowShop(ctx context.Context, userID, shopID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnfollowShop", ctx, userID, shopID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnfollowShop indicates an expected call of UnfollowShop.
func (mr *MockUserRepositoryMockRecorder) UnfollowShop(ctx, userID, shopID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnfollowShop", reflect.TypeOf((*MockUserRepository)(nil).UnfollowShop), ctx, userID, shopID)
}

// UnlikeShop mocks base method.
func (m *MockUserRepository) UnlikeShop(ctx context.Context, userID, shopID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnlikeShop", ctx, userID, shopID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnlikeShop indicates an expected call of UnlikeShop.
func (mr *MockUserRepositoryMockRecorder) UnlikeShop(ctx, userID, shopID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnlikeShop", reflect.TypeOf((*MockUserRepository)(nil).UnlikeShop), ctx, userID, shopID)
}

// UpdateAddress mocks base method.
func (m *MockUserRepository) UpdateAddress(ctx context.Context, address domain.Address) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAddress", ctx, address)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAddress indicates an expected call of UpdateAddress.
func (mr *MockUserRepositoryMockRecorder) UpdateAddress(ctx, address interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAddress", reflect.TypeOf((*MockUserRepository)(nil).UpdateAddress), ctx, address)
}

// UpdateAdminVerified mocks base method.
func (m *MockUserRepository) UpdateAdminVerified(ctx context.Context, adminID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAdminVerified", ctx, adminID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAdminVerified indicates an expected call of UpdateAdminVerified.
func (mr *MockUserRepositoryMockRecorder) UpdateAdminVerified(ctx, adminID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAdminVerified", reflect.TypeOf((*MockUserRepository)(nil).UpdateAdminVerified), ctx, adminID)
}

// UpdateBlockStatus mocks base method.
func (m *MockUserRepository) UpdateBlockStatus(ctx context.Context, userID string, blockStatus bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBlockStatus", ctx, userID, blockStatus)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBlockStatus indicates an expected call of UpdateBlockStatus.
func (mr *MockUserRepositoryMockRecorder) UpdateBlockStatus(ctx, userID, blockStatus interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBlockStatus", reflect.TypeOf((*MockUserRepository)(nil).UpdateBlockStatus), ctx, userID, blockStatus)
}

// UpdateTrialUsed mocks base method.
func (m *MockUserRepository) UpdateTrialUsed(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTrialUsed", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTrialUsed indicates an expected call of UpdateTrialUsed.
func (mr *MockUserRepositoryMockRecorder) UpdateTrialUsed(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTrialUsed", reflect.TypeOf((*MockUserRepository)(nil).UpdateTrialUsed), ctx, userID)
}

// UpdateUser mocks base method.
func (m *MockUserRepository) UpdateUser(ctx context.Context, user domain.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockUserRepositoryMockRecorder) UpdateUser(ctx, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockUserRepository)(nil).UpdateUser), ctx, user)
}

// UpdateUserAddress mocks base method.
func (m *MockUserRepository) UpdateUserAddress(ctx context.Context, userAddress domain.UserAddress) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserAddress", ctx, userAddress)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserAddress indicates an expected call of UpdateUserAddress.
func (mr *MockUserRepositoryMockRecorder) UpdateUserAddress(ctx, userAddress interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserAddress", reflect.TypeOf((*MockUserRepository)(nil).UpdateUserAddress), ctx, userAddress)
}

// UpdateVerified mocks base method.
func (m *MockUserRepository) UpdateVerified(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateVerified", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateVerified indicates an expected call of UpdateVerified.
func (mr *MockUserRepositoryMockRecorder) UpdateVerified(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateVerified", reflect.TypeOf((*MockUserRepository)(nil).UpdateVerified), ctx, userID)
}
