// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/rohit221990/mandi-backend/pkg/api"
	"github.com/rohit221990/mandi-backend/pkg/api/handler"
	"github.com/rohit221990/mandi-backend/pkg/api/middleware"
	"github.com/rohit221990/mandi-backend/pkg/config"
	"github.com/rohit221990/mandi-backend/pkg/db"
	"github.com/rohit221990/mandi-backend/pkg/repository"
	"github.com/rohit221990/mandi-backend/pkg/service/ai"
	"github.com/rohit221990/mandi-backend/pkg/service/alert_engine"
	"github.com/rohit221990/mandi-backend/pkg/service/cloud"
	"github.com/rohit221990/mandi-backend/pkg/service/crypto"
	"github.com/rohit221990/mandi-backend/pkg/service/elasticsearch"
	"github.com/rohit221990/mandi-backend/pkg/service/graphics"
	"github.com/rohit221990/mandi-backend/pkg/service/otp"
	"github.com/rohit221990/mandi-backend/pkg/service/token"
	"github.com/rohit221990/mandi-backend/pkg/usecase"
)

// Injectors from wire.go:

func InitializeApi(cfg config.Config) (*http.ServerHTTP, error) {
	gormDB, err := db.ConnectDatabase(cfg)
	if err != nil {
		return nil, err
	}
	authRepository := repository.NewAuthRepository(gormDB)
	tokenService := token.NewTokenService(cfg)
	userRepository := repository.NewUserRepository(gormDB)
	service, err := provideCryptoService(cfg)
	if err != nil {
		return nil, err
	}
	adminRepository := repository.NewAdminRepository(gormDB, service)
	otpAuth := otp.NewOtpAuth(cfg)
	authUseCase := usecase.NewAuthUseCase(authRepository, tokenService, userRepository, adminRepository, otpAuth)
	authHandler := handler.NewAuthHandler(authUseCase, cfg, tokenService)
	middlewareMiddleware := middleware.NewMiddleware(tokenService)
	adminUseCase := usecase.NewAdminUseCase(adminRepository, userRepository, authRepository, otpAuth, tokenService)
	shopTimeRepository := repository.NewShopTimeRepository(gormDB)
	shopTimeUseCase := usecase.NewShopTimeUseCase(shopTimeRepository)
	adminHandler := handler.NewAdminHandler(adminUseCase, shopTimeUseCase)
	cartRepository := repository.NewCartRepository(gormDB)
	string2 := provideElasticURL(cfg)
	elasticService, err := elasticsearch.NewElasticService(string2)
	if err != nil {
		return nil, err
	}
	productRepository := repository.NewProductRepository(gormDB, elasticService)
	cloudService, err := cloud.NewAWSCloudService(cfg)
	if err != nil {
		return nil, err
	}
	userUseCase := usecase.NewUserUseCase(userRepository, cartRepository, productRepository, cloudService)
	userHandler := handler.NewUserHandler(userUseCase)
	cartUseCase := usecase.NewCartUseCase(cartRepository, productRepository)
	cartHandler := handler.NewCartHandler(cartUseCase)
	paymentRepository := repository.NewPaymentRepository(gormDB)
	orderRepository := repository.NewOrderRepository(gormDB)
	couponRepository := repository.NewCouponRepository(gormDB)
	paymentUseCase := usecase.NewPaymentUseCase(paymentRepository, orderRepository, userRepository, cartRepository, couponRepository, cfg)
	paymentHandler := handler.NewPaymentHandler(paymentUseCase)
	productUseCase := usecase.NewProductUseCase(productRepository, cloudService, gormDB)
	client := provideAIServiceClient(cfg)
	productHandler := handler.NewProductHandler(productUseCase, tokenService, client)
	orderUseCase := usecase.NewOrderUseCase(orderRepository, cartRepository, userRepository, paymentRepository)
	orderHandler := handler.NewOrderHandler(orderUseCase)
	couponUseCase := usecase.NewCouponUseCase(couponRepository, cartRepository)
	couponHandler := handler.NewCouponHandler(couponUseCase)
	offerRepository := repository.NewOfferRepository(gormDB)
	bannerRepository := repository.NewBannerRepository(gormDB)
	graphicsService := graphics.NewGraphicsService(string2)
	offerUseCase := usecase.NewOfferUseCase(offerRepository, bannerRepository, gormDB, graphicsService)
	offerHandler := handler.NewOfferHandler(offerUseCase, tokenService)
	stockRepository := repository.NewStockRepository(gormDB)
	stockUseCase := usecase.NewStockUseCase(stockRepository)
	stockHandler := handler.NewStockHandler(stockUseCase)
	brandRepository := repository.NewBrandDatabaseRepository(gormDB)
	brandUseCase := usecase.NewBrandUseCase(brandRepository)
	brandHandler := handler.NewBrandHandler(brandUseCase)
	notificationRepository := repository.NewNotificationRepository(gormDB)
	notificationUseCase := usecase.NewNotificationUseCase(notificationRepository, cfg)
	notificationHandler := handler.NewNotificationHandler(notificationUseCase)
	promotionRepository := repository.NewPromotionRepository(gormDB)
	promotionUseCase := usecase.NewPromotionUseCase(promotionRepository)
	promotionHandler := handler.NewPromotionHandler(promotionUseCase)
	fcmTokenRepository := repository.NewFcmTokenRepository(gormDB)
	fcmTokenUseCase := usecase.NewFcmTokenUseCase(fcmTokenRepository, tokenService)
	fcmTokenHandler := handler.NewFcmTokenHandler(fcmTokenUseCase)
	searchRepository := repository.NewSearchRepository(gormDB, elasticService)
	searchUseCase := usecase.NewSearchUseCase(searchRepository)
	searchHandler := handler.NewSearchHandler(searchUseCase)
	alertRepository := repository.NewAlertRepository(gormDB)
	ruleRegistry := provideAlertRuleRegistry()
	alertUseCase := usecase.NewAlertUseCase(alertRepository, ruleRegistry)
	alertHandler := handler.NewAlertHandler(alertUseCase, adminUseCase)
	uiHandler := handler.NewUIHandler(adminUseCase)
	alertTemplateUseCase := usecase.NewAlertTemplateUseCase(alertRepository)
	alertTemplateHandler := handler.NewAlertTemplateHandler(alertTemplateUseCase, adminUseCase)
	bannerUseCase := usecase.NewBannerUseCase(bannerRepository)
	bannerUserHandler := handler.NewBannerUserHandler(bannerUseCase)
	subscriptionRepository := repository.NewSubscriptionRepository(gormDB)
	subscriptionPaymentUseCase := usecase.NewSubscriptionPaymentUseCase(subscriptionRepository, paymentRepository, userRepository, cfg)
	subscriptionPaymentHandler := handler.NewSubscriptionPaymentHandler(subscriptionPaymentUseCase)
	subscriptionUseCase := usecase.NewSubscriptionUseCase(subscriptionRepository, userRepository)
	subscriptionHandler := handler.NewSubscriptionHandler(subscriptionUseCase)
	serverHTTP := http.NewServerHTTP(authHandler, middlewareMiddleware, adminHandler, userHandler, cartHandler, paymentHandler, productHandler, orderHandler, couponHandler, offerHandler, stockHandler, brandHandler, notificationHandler, promotionHandler, fcmTokenHandler, searchHandler, alertHandler, uiHandler, alertTemplateHandler, bannerUserHandler, subscriptionPaymentHandler, subscriptionHandler)
	return serverHTTP, nil
}

// wire.go:

func provideElasticURL(cfg config.Config) string {
	return cfg.ElasticsearchURL
}

func provideAIServiceClient(cfg config.Config) *ai.Client {
	return ai.NewClient(cfg.AIServiceURL)
}

func provideCryptoService(cfg config.Config) (*crypto.Service, error) {
	keys, err := crypto.ParseKeyring(cfg.PIIEncryptionKeys)
	if err != nil {
		return nil, err
	}
	return crypto.NewService(keys, cfg.PIIEncryptionActiveKey)
}

func provideAlertRuleRegistry() *alert_engine.RuleRegistry {
	registry := alert_engine.NewRuleRegistry()

	registry.RegisterMultiple(alert_engine.MissingShopPhotoRule{}, alert_engine.NoProductsRule{}, alert_engine.ShopNotVerifiedRule{})
	return registry
}
