// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	http "github.com/rohit221990/mandi-backend/pkg/api"
	"github.com/rohit221990/mandi-backend/pkg/api/handler"
	"github.com/rohit221990/mandi-backend/pkg/api/middleware"
	"github.com/rohit221990/mandi-backend/pkg/config"
	"github.com/rohit221990/mandi-backend/pkg/db"
	"github.com/rohit221990/mandi-backend/pkg/repository"
	"github.com/rohit221990/mandi-backend/pkg/service/cloud"
	elasticsearch "github.com/rohit221990/mandi-backend/pkg/service/elasticsearch"
	"github.com/rohit221990/mandi-backend/pkg/service/graphics"
	"github.com/rohit221990/mandi-backend/pkg/service/otp"
	"github.com/rohit221990/mandi-backend/pkg/service/token"
	"github.com/rohit221990/mandi-backend/pkg/usecase"
)

// Injectors from wire.go:

func InitializeApi(cfg config.Config) (*http.ServerHTTP, error) {
	gormDB, err := db.ConnectDatabase(cfg)
	if err != nil {
		return nil, err
	}
	var elasticService *elasticsearch.ElasticService
	if cfg.ElasticsearchURL != "" {
		elasticService, err = elasticsearch.NewElasticService(cfg.ElasticsearchURL)
		if err != nil {
			return nil, err
		}
	}
	authRepository := repository.NewAuthRepository(gormDB)
	tokenService := token.NewTokenService(cfg)
	userRepository := repository.NewUserRepository(gormDB)
	adminRepository := repository.NewAdminRepository(gormDB)
	otpAuth := otp.NewOtpAuth(cfg)
	authUseCase := usecase.NewAuthUseCase(authRepository, tokenService, userRepository, adminRepository, otpAuth)
	authHandler := handler.NewAuthHandler(authUseCase, cfg, tokenService)
	middlewareMiddleware := middleware.NewMiddleware(tokenService)
	adminUseCase := usecase.NewAdminUseCase(adminRepository, userRepository, authRepository, otpAuth, tokenService)
	adminHandler := handler.NewAdminHandler(adminUseCase)
	cartRepository := repository.NewCartRepository(gormDB)
	productRepository := repository.NewProductRepository(gormDB, elasticService)
	cloudService, err := cloud.NewAWSCloudService(cfg)
	if err != nil {
		return nil, err
	}
	userUseCase := usecase.NewUserUseCase(userRepository, cartRepository, productRepository, cloudService)
	userHandler := handler.NewUserHandler(userUseCase)
	cartUseCase := usecase.NewCartUseCase(cartRepository, productRepository)
	cartHandler := handler.NewCartHandler(cartUseCase)
	paymentRepository := repository.NewPaymentRepository(gormDB)
	orderRepository := repository.NewOrderRepository(gormDB)
	couponRepository := repository.NewCouponRepository(gormDB)
	paymentUseCase := usecase.NewPaymentUseCase(paymentRepository, orderRepository, userRepository, cartRepository, couponRepository, cfg)
	paymentHandler := handler.NewPaymentHandler(paymentUseCase)
	productUseCase := usecase.NewProductUseCase(productRepository, cloudService, gormDB)
	productHandler := handler.NewProductHandler(productUseCase, tokenService)
	orderUseCase := usecase.NewOrderUseCase(orderRepository, cartRepository, userRepository, paymentRepository)
	orderHandler := handler.NewOrderHandler(orderUseCase)
	couponUseCase := usecase.NewCouponUseCase(couponRepository, cartRepository)
	couponHandler := handler.NewCouponHandler(couponUseCase)
	offerRepository := repository.NewOfferRepository(gormDB)
	graphicsService := graphics.NewGraphicsService("./uploads/offers")
	offerUseCase := usecase.NewOfferUseCase(offerRepository, gormDB, graphicsService)
	offerHandler := handler.NewOfferHandler(offerUseCase, tokenService)
	stockRepository := repository.NewStockRepository(gormDB)
	stockUseCase := usecase.NewStockUseCase(stockRepository)
	stockHandler := handler.NewStockHandler(stockUseCase)
	brandRepository := repository.NewBrandDatabaseRepository(gormDB)
	brandUseCase := usecase.NewBrandUseCase(brandRepository)
	brandHandler := handler.NewBrandHandler(brandUseCase)
	promotionRepository := repository.NewPromotionRepository(gormDB)
	promotionUseCase := usecase.NewPromotionUseCase(promotionRepository)
	promotionHandler := handler.NewPromotionHandler(promotionUseCase)
	notificationRepository := repository.NewNotificationRepository(gormDB)
	notificationUseCase := usecase.NewNotificationUseCase(notificationRepository)
	notificationHandler := handler.NewNotificationHandler(notificationUseCase)
	serverHTTP := http.NewServerHTTP(authHandler, middlewareMiddleware, adminHandler, userHandler, cartHandler, paymentHandler, productHandler, orderHandler, couponHandler, offerHandler, stockHandler, brandHandler, notificationHandler, promotionHandler)
	return serverHTTP, nil
}
