// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rohit221990/mandi-backend/pkg/usecase/interfaces (interfaces: AuthUseCase)

// Package mockusecase is a generated GoMock package.
package mockusecase

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	request "github.com/rohit221990/mandi-backend/pkg/api/handler/request"
	domain "github.com/rohit221990/mandi-backend/pkg/domain"
	token "github.com/rohit221990/mandi-backend/pkg/service/token"
	interfaces "github.com/rohit221990/mandi-backend/pkg/usecase/interfaces"
)

// MockAuthUseCase is a mock of AuthUseCase interface.
type MockAuthUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockAuthUseCaseMockRecorder
}

// MockAuthUseCaseMockRecorder is the mock recorder for MockAuthUseCase.
type MockAuthUseCaseMockRecorder struct {
	mock *MockAuthUseCase
}

// NewMockAuthUseCase creates a new mock instance.
func NewMockAuthUseCase(ctrl *gomock.Controller) *MockAuthUseCase {
	mock := &MockAuthUseCase{ctrl: ctrl}
	mock.recorder = &MockAuthUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthUseCase) EXPECT() *MockAuthUseCaseMockRecorder {
	return m.recorder
}

// AdminLogin mocks base method.
func (m *MockAuthUseCase) AdminLogin(arg0 context.Context, arg1 request.Login) (domain.Admin, domain.ShopVerification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdminLogin", arg0, arg1)
	ret0, _ := ret[0].(domain.Admin)
	ret1, _ := ret[1].(domain.ShopVerification)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// AdminLogin indicates an expected call of AdminLogin.
func (mr *MockAuthUseCaseMockRecorder) AdminLogin(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminLogin", reflect.TypeOf((*MockAuthUseCase)(nil).AdminLogin), arg0, arg1)
}

// GenerateAccessToken mocks base method.
func (m *MockAuthUseCase) GenerateAccessToken(arg0 context.Context, arg1 interfaces.GenerateTokenParams) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateAccessToken", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateAccessToken indicates an expected call of GenerateAccessToken.
func (mr *MockAuthUseCaseMockRecorder) GenerateAccessToken(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateAccessToken", reflect.TypeOf((*MockAuthUseCase)(nil).GenerateAccessToken), arg0, arg1)
}

// GenerateRefreshToken mocks base method.
func (m *MockAuthUseCase) GenerateRefreshToken(arg0 context.Context, arg1 interfaces.GenerateTokenParams) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateRefreshToken", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateRefreshToken indicates an expected call of GenerateRefreshToken.
func (mr *MockAuthUseCaseMockRecorder) GenerateRefreshToken(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateRefreshToken", reflect.TypeOf((*MockAuthUseCase)(nil).GenerateRefreshToken), arg0, arg1)
}

// GoogleLogin mocks base method.
func (m *MockAuthUseCase) GoogleLogin(arg0 context.Context, arg1 domain.User) (uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GoogleLogin", arg0, arg1)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GoogleLogin indicates an expected call of GoogleLogin.
func (mr *MockAuthUseCaseMockRecorder) GoogleLogin(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GoogleLogin", reflect.TypeOf((*MockAuthUseCase)(nil).GoogleLogin), arg0, arg1)
}

// LoginOtpVerify mocks base method.
func (m *MockAuthUseCase) LoginOtpVerify(arg0 context.Context, arg1 request.OTPVerify) (uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoginOtpVerify", arg0, arg1)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoginOtpVerify indicates an expected call of LoginOtpVerify.
func (mr *MockAuthUseCaseMockRecorder) LoginOtpVerify(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoginOtpVerify", reflect.TypeOf((*MockAuthUseCase)(nil).LoginOtpVerify), arg0, arg1)
}

// LoginOtpVerifyEmail mocks base method.
func (m *MockAuthUseCase) LoginOtpVerifyEmail(arg0 context.Context, arg1 request.OTPVerify) (uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoginOtpVerifyEmail", arg0, arg1)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoginOtpVerifyEmail indicates an expected call of LoginOtpVerifyEmail.
func (mr *MockAuthUseCaseMockRecorder) LoginOtpVerifyEmail(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoginOtpVerifyEmail", reflect.TypeOf((*MockAuthUseCase)(nil).LoginOtpVerifyEmail), arg0, arg1)
}

// SingUpOtpVerify mocks base method.
func (m *MockAuthUseCase) SingUpOtpVerify(arg0 context.Context, arg1 request.OTPVerify) (uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SingUpOtpVerify", arg0, arg1)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SingUpOtpVerify indicates an expected call of SingUpOtpVerify.
func (mr *MockAuthUseCaseMockRecorder) SingUpOtpVerify(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SingUpOtpVerify", reflect.TypeOf((*MockAuthUseCase)(nil).SingUpOtpVerify), arg0, arg1)
}

// UserLogin mocks base method.
func (m *MockAuthUseCase) UserLogin(arg0 context.Context, arg1 request.Login) (uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserLogin", arg0, arg1)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserLogin indicates an expected call of UserLogin.
func (mr *MockAuthUseCaseMockRecorder) UserLogin(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserLogin", reflect.TypeOf((*MockAuthUseCase)(nil).UserLogin), arg0, arg1)
}

// UserLoginOtpSend mocks base method.
func (m *MockAuthUseCase) UserLoginOtpSend(arg0 context.Context, arg1 request.OTPLogin) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserLoginOtpSend", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserLoginOtpSend indicates an expected call of UserLoginOtpSend.
func (mr *MockAuthUseCaseMockRecorder) UserLoginOtpSend(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserLoginOtpSend", reflect.TypeOf((*MockAuthUseCase)(nil).UserLoginOtpSend), arg0, arg1)
}

// UserLoginOtpSendEmail mocks base method.
func (m *MockAuthUseCase) UserLoginOtpSendEmail(arg0 context.Context, arg1 request.OTPLoginEmail) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserLoginOtpSendEmail", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserLoginOtpSendEmail indicates an expected call of UserLoginOtpSendEmail.
func (mr *MockAuthUseCaseMockRecorder) UserLoginOtpSendEmail(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserLoginOtpSendEmail", reflect.TypeOf((*MockAuthUseCase)(nil).UserLoginOtpSendEmail), arg0, arg1)
}

// UserLogout mocks base method.
func (m *MockAuthUseCase) UserLogout(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserLogout", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UserLogout indicates an expected call of UserLogout.
func (mr *MockAuthUseCaseMockRecorder) UserLogout(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserLogout", reflect.TypeOf((*MockAuthUseCase)(nil).UserLogout), arg0, arg1, arg2)
}

// UserSignUp mocks base method.
func (m *MockAuthUseCase) UserSignUp(arg0 context.Context, arg1 domain.User) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserSignUp", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserSignUp indicates an expected call of UserSignUp.
func (mr *MockAuthUseCaseMockRecorder) UserSignUp(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserSignUp", reflect.TypeOf((*MockAuthUseCase)(nil).UserSignUp), arg0, arg1)
}

// VerifyAndGetRefreshTokenSession mocks base method.
func (m *MockAuthUseCase) VerifyAndGetRefreshTokenSession(arg0 context.Context, arg1 string, arg2 token.UserType) (domain.RefreshSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyAndGetRefreshTokenSession", arg0, arg1, arg2)
	ret0, _ := ret[0].(domain.RefreshSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyAndGetRefreshTokenSession indicates an expected call of VerifyAndGetRefreshTokenSession.
func (mr *MockAuthUseCaseMockRecorder) VerifyAndGetRefreshTokenSession(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyAndGetRefreshTokenSession", reflect.TypeOf((*MockAuthUseCase)(nil).VerifyAndGetRefreshTokenSession), arg0, arg1, arg2)
}
