// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/usecase/interfaces/invoice.go

// Package mockusecase is a generated GoMock package.
package mockusecase

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	domain "github.com/rohit221990/mandi-backend/pkg/domain"
)

// MockInvoiceUseCase is a mock of InvoiceUseCase interface.
type MockInvoiceUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockInvoiceUseCaseMockRecorder
}

// MockInvoiceUseCaseMockRecorder is the mock recorder for MockInvoiceUseCase.
type MockInvoiceUseCaseMockRecorder struct {
	mock *MockInvoiceUseCase
}

// NewMockInvoiceUseCase creates a new mock instance.
func NewMockInvoiceUseCase(ctrl *gomock.Controller) *MockInvoiceUseCase {
	mock := &MockInvoiceUseCase{ctrl: ctrl}
	mock.recorder = &MockInvoiceUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInvoiceUseCase) EXPECT() *MockInvoiceUseCaseMockRecorder {
	return m.recorder
}

// GetCompanyBillingProfile mocks base method.
func (m *MockInvoiceUseCase) GetCompanyBillingProfile(ctx context.Context) (domain.CompanyBillingProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCompanyBillingProfile", ctx)
	ret0, _ := ret[0].(domain.CompanyBillingProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCompanyBillingProfile indicates an expected call of GetCompanyBillingProfile.
func (mr *MockInvoiceUseCaseMockRecorder) GetCompanyBillingProfile(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCompanyBillingProfile", reflect.TypeOf((*MockInvoiceUseCase)(nil).GetCompanyBillingProfile), ctx)
}

// UpdateCompanyBillingProfile mocks base method.
func (m *MockInvoiceUseCase) UpdateCompanyBillingProfile(ctx context.Context, profile domain.CompanyBillingProfile) (domain.CompanyBillingProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCompanyBillingProfile", ctx, profile)
	ret0, _ := ret[0].(domain.CompanyBillingProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCompanyBillingProfile indicates an expected call of UpdateCompanyBillingProfile.
func (mr *MockInvoiceUseCaseMockRecorder) UpdateCompanyBillingProfile(ctx, profile interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCompanyBillingProfile", reflect.TypeOf((*MockInvoiceUseCase)(nil).UpdateCompanyBillingProfile), ctx, profile)
}
