-- Insert category images
-- Generated by generate_category_images.py

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (1, '/uploads/category-images/category_1.png', 'Fasteners Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (2, '/uploads/category-images/category_2.png', 'Plumbing Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (3, '/uploads/category-images/category_3.png', 'Electrical Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (4, '/uploads/category-images/category_4.png', 'Paints Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (5, '/uploads/category-images/category_5.png', 'Power Tools Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (6, '/uploads/category-images/category_6.png', 'Hand Tools Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (7, '/uploads/category-images/category_7.png', 'Hardware Accessories Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (8, '/uploads/category-images/category_8.png', 'Ladders & Platforms Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (9, '/uploads/category-images/category_9.png', 'Measuring Tools Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (10, '/uploads/category-images/category_10.png', 'Cutting Tools Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (11, '/uploads/category-images/category_11.png', 'Safety Equipment Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (12, '/uploads/category-images/category_12.png', 'Garden Tools Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (13, '/uploads/category-images/category_13.png', 'Welding Supplies Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (14, '/uploads/category-images/category_14.png', 'Adhesives & Sealants Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (15, '/uploads/category-images/category_15.png', 'Others Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (16, '/uploads/category-images/category_16.png', 'Building Materials Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (17, '/uploads/category-images/category_17.png', 'Steel & Metals Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (18, '/uploads/category-images/category_18.png', 'Wood & Timber Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (19, '/uploads/category-images/category_19.png', 'Roofing Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (20, '/uploads/category-images/category_20.png', 'Civil Supplies Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (21, '/uploads/category-images/category_21.png', 'Cement & Concrete Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (22, '/uploads/category-images/category_22.png', 'Sand & Aggregates Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (23, '/uploads/category-images/category_23.png', 'Bricks & Blocks Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (24, '/uploads/category-images/category_24.png', 'Doors & Windows Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (25, '/uploads/category-images/category_25.png', 'Plywood & Laminates Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (26, '/uploads/category-images/category_26.png', 'Gypsum & Plaster Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (27, '/uploads/category-images/category_27.png', 'Tiles & Flooring Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (28, '/uploads/category-images/category_28.png', 'Structural Steel Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (29, '/uploads/category-images/category_29.png', 'Pipes & Fittings Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (30, '/uploads/category-images/category_30.png', 'Construction Chemicals Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (31, '/uploads/category-images/category_31.png', 'Others Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (32, '/uploads/category-images/category_32.png', 'Living Room Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (33, '/uploads/category-images/category_33.png', 'Bedroom Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (34, '/uploads/category-images/category_34.png', 'Kitchen Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (35, '/uploads/category-images/category_35.png', 'Office Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (36, '/uploads/category-images/category_36.png', 'Outdoor Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (37, '/uploads/category-images/category_37.png', 'Dining Room Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (38, '/uploads/category-images/category_38.png', 'Mattresses Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (39, '/uploads/category-images/category_39.png', 'Sofas & Recliners Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (40, '/uploads/category-images/category_40.png', 'Beds Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (41, '/uploads/category-images/category_41.png', 'Wardrobes Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (42, '/uploads/category-images/category_42.png', 'Tables Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (43, '/uploads/category-images/category_43.png', 'Chairs Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (44, '/uploads/category-images/category_44.png', 'Cabinets & Storage Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (45, '/uploads/category-images/category_45.png', 'TV Units & Entertainment Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (46, '/uploads/category-images/category_46.png', 'Bookcases & Shelves Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (47, '/uploads/category-images/category_47.png', 'Others Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (48, '/uploads/category-images/category_48.png', 'Mobiles Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (49, '/uploads/category-images/category_49.png', 'Tablets Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (50, '/uploads/category-images/category_50.png', 'Laptops Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (51, '/uploads/category-images/category_51.png', 'Desktops Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (52, '/uploads/category-images/category_52.png', 'Televisions Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (53, '/uploads/category-images/category_53.png', 'Home Appliances Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (54, '/uploads/category-images/category_54.png', 'Kitchen Appliances Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (55, '/uploads/category-images/category_55.png', 'Audio Systems Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (56, '/uploads/category-images/category_56.png', 'Cameras Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (57, '/uploads/category-images/category_57.png', 'Gaming Consoles Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (58, '/uploads/category-images/category_58.png', 'Accessories Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (59, '/uploads/category-images/category_59.png', 'Networking Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (60, '/uploads/category-images/category_60.png', 'Smart Home Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (61, '/uploads/category-images/category_61.png', 'Wearables Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (62, '/uploads/category-images/category_62.png', 'Printers & Scanners Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (63, '/uploads/category-images/category_63.png', 'Storage Devices Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (64, '/uploads/category-images/category_64.png', 'Speakers Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (65, '/uploads/category-images/category_65.png', 'Headphones Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (66, '/uploads/category-images/category_66.png', 'Power Banks Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (67, '/uploads/category-images/category_67.png', 'Fans & Coolers Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (68, '/uploads/category-images/category_68.png', 'Others Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (69, '/uploads/category-images/category_69.png', 'Staples Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (70, '/uploads/category-images/category_70.png', 'Snacks Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (71, '/uploads/category-images/category_71.png', 'Beverages Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (72, '/uploads/category-images/category_72.png', 'Household Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (73, '/uploads/category-images/category_73.png', 'Dairy Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (74, '/uploads/category-images/category_74.png', 'Bakery Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (75, '/uploads/category-images/category_75.png', 'Spices & Masalas Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (76, '/uploads/category-images/category_76.png', 'Cooking Essentials Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (77, '/uploads/category-images/category_77.png', 'Personal Care Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (78, '/uploads/category-images/category_78.png', 'Baby Products Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (79, '/uploads/category-images/category_79.png', 'Health & Wellness Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (80, '/uploads/category-images/category_80.png', 'Frozen Foods Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (81, '/uploads/category-images/category_81.png', 'Ready to Eat Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (82, '/uploads/category-images/category_82.png', 'Organic Products Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (83, '/uploads/category-images/category_83.png', 'Fruits & Vegetables Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (84, '/uploads/category-images/category_84.png', 'Sweets & Mithai Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (85, '/uploads/category-images/category_85.png', 'Pet Supplies Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (86, '/uploads/category-images/category_86.png', 'Others Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (87, '/uploads/category-images/category_87.png', 'Office Supplies Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (88, '/uploads/category-images/category_88.png', 'School Supplies Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (89, '/uploads/category-images/category_89.png', 'Art Materials Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (90, '/uploads/category-images/category_90.png', 'Packaging Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (91, '/uploads/category-images/category_91.png', 'Writing Instruments Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (92, '/uploads/category-images/category_92.png', 'Notebooks & Diaries Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (93, '/uploads/category-images/category_93.png', 'Files & Folders Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (94, '/uploads/category-images/category_94.png', 'Desk Accessories Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (95, '/uploads/category-images/category_95.png', 'Printer Supplies Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (96, '/uploads/category-images/category_96.png', 'Drawing & Drafting Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (97, '/uploads/category-images/category_97.png', 'Craft Supplies Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (98, '/uploads/category-images/category_98.png', 'Whiteboards & Boards Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (99, '/uploads/category-images/category_99.png', 'Calculators Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (100, '/uploads/category-images/category_100.png', 'Presentation Supplies Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (101, '/uploads/category-images/category_101.png', 'Correction Supplies Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (102, '/uploads/category-images/category_102.png', 'Sticky Notes & Tapes Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (103, '/uploads/category-images/category_103.png', 'Envelopes & Labels Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (104, '/uploads/category-images/category_104.png', 'Others Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (105, '/uploads/category-images/category_105.png', 'Shirts Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (106, '/uploads/category-images/category_106.png', 'Pants Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (107, '/uploads/category-images/category_107.png', 'Suits Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (108, '/uploads/category-images/category_108.png', 'Accessory Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (109, '/uploads/category-images/category_109.png', 'Dresses Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (110, '/uploads/category-images/category_110.png', 'Tops Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (111, '/uploads/category-images/category_111.png', 'Bottoms Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (112, '/uploads/category-images/category_112.png', 'Lingerie Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (113, '/uploads/category-images/category_113.png', 'Infants Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (114, '/uploads/category-images/category_114.png', 'Toddlers Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (115, '/uploads/category-images/category_115.png', 'Juniors Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (116, '/uploads/category-images/category_116.png', 'Gym Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (117, '/uploads/category-images/category_117.png', 'Outerwear Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (118, '/uploads/category-images/category_118.png', 'Women Sportswear Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (119, '/uploads/category-images/category_119.png', 'Mens Sportswear Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (120, '/uploads/category-images/category_120.png', 'Ethnic Wear Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (121, '/uploads/category-images/category_121.png', 'Formal Wear Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (122, '/uploads/category-images/category_122.png', 'Casual Wear Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (123, '/uploads/category-images/category_123.png', 'Sleepwear Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (124, '/uploads/category-images/category_124.png', 'Swimwear Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (125, '/uploads/category-images/category_125.png', 'Winter Wear Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (126, '/uploads/category-images/category_126.png', 'Footwear Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (127, '/uploads/category-images/category_127.png', 'Bags Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (128, '/uploads/category-images/category_128.png', 'Jewelry Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (129, '/uploads/category-images/category_129.png', 'Sunglasses Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (130, '/uploads/category-images/category_130.png', 'Watches Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (131, '/uploads/category-images/category_131.png', 'Innerwear Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (132, '/uploads/category-images/category_132.png', 'Plus Size Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (133, '/uploads/category-images/category_133.png', 'Bridal Wear Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (134, '/uploads/category-images/category_134.png', 'Party Wear Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

INSERT INTO category_images (category_id, image_url, alt_text, sort_order) 
VALUES (135, '/uploads/category-images/category_135.png', 'Others Category', 0)
ON CONFLICT (category_id, image_url) DO NOTHING;

